lukniewiara_news_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: lukniewiaraNewsBundle:Default:index }
    
lukniewiaraNewsBundle_news:
    resource: "@lukniewiaraNewsBundle/Resources/config/routing/news.yml"
    prefix:   /news
