parameters:
#    lukniewiara_news.example.class: lukniewiara\NewsBundle\Example

services:
#    lukniewiara_news.example:
#        class: %lukniewiara_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
